colours:
  PenguinJ2: "AQUA"
  MrSugarCaney: "GREEN"
teams:
  example_team:
    members:
    - example_member_1
    - example_member_2
    color: "GREEN"
  example_team_2:
    members:
    - example_member_3
    - example_member_4
    color: "GOLD"