name: GM4UHC
main: co.gm4.uhc.GM4UHC
authors: [MrSugarCaney]
version: '1.0'
description: >
             Gamemode 4 UHC plugin
commands:
  uhc:
    description: Gamemode 4 UHC Help
    permission: uhc.mod
  gm4:
    description: Gamemode 4 Info
  shout:
    description: Broadcast a message to all players.
    permission: uhc.mod
    aliases: [broadcast]