name: GM4UHC
main: co.gm4.uhc.GM4UHC
authors: [MrSugarCaney]
version: '1.0'
description: >
             Gamemode 4 UHC plugin
commands:
  uhc:
    description: Gamemode 4 UHC
    permission: gm4.mod
  gm4:
    description: Gamemode 4 UHC
    permission: gm4.mod